// Bank-ready PDF report template for the Solar Green Loan Calculator lead.
// Mirrors the existing HTML→PDF pipeline used by src/lib/report-data.ts +
// src/app/api/reports/[id]/pdf/route.ts (Playwright via scripts/html-to-pdf.js),
// so the new public calculator produces documents consistent with the rest
// of the platform's report output.

import crypto from 'crypto'
import QRCode from 'qrcode'
import type { SolarCalculatorResult } from './solar-engine'

export interface SolarLeadReportInput {
  id: string
  reportToken: string
  fullName: string
  email: string
  phone?: string | null
  companyName?: string | null
  userType: string // individual | sme
  countryCode: string
  createdAt: Date
  result: SolarCalculatorResult
  verifyUrl: string // public URL the QR code / stamp resolves to
}

/**
 * Deterministic SHA-256 fingerprint of the report's material figures.
 * This is NOT a Hedera/blockchain attestation (unlike src/lib/canonical-hash.ts,
 * used for inverter readings that ARE submitted to Hedera) — it is a
 * lightweight, verifiable "this PDF was generated by EcoLedger's calculator
 * with exactly these inputs/outputs" stamp a bank can check against the
 * lead record via `verifyUrl`. Labeled "Blockchain-Ready" because the same
 * hash can be submitted to Hedera later (see src/lib/hedera.ts) if/when this
 * lead converts into a real monitored project — it is not itself on-chain yet.
 */
export function computeReportVerificationHash(input: Omit<SolarLeadReportInput, 'verifyUrl'>): string {
  const r = input.result
  const canonical = [
    input.id,
    input.reportToken,
    input.email.trim().toLowerCase(),
    input.userType,
    input.countryCode,
    input.createdAt.toISOString(),
    r.loan.estimatedSystemCost,
    r.loan.loanAmount,
    r.loan.monthlyPMT,
    r.cashflow.monthlySavings,
    r.cashflow.simplePaybackYears,
    r.cashflow.cumulativeROI20yrPct,
    r.carbon.avoidedCO2TonsLifetime,
  ].join('|')
  return crypto.createHash('sha256').update(canonical).digest('hex')
}

const fmtMoney = (n: number, currency: string) =>
  `${Math.round(n).toLocaleString('en-US')} ${currency}`
const fmtNum = (n: number) => n.toLocaleString('en-US', { maximumFractionDigits: 1 })

export async function generateSolarLeadReportHTML(input: SolarLeadReportInput): Promise<string> {
  const { result: r } = input
  const verificationHash = computeReportVerificationHash(input)
  const qrCodeDataUrl = await QRCode.toDataURL(input.verifyUrl, { width: 150, margin: 1 })
  const userTypeLabel = input.userType === 'sme' ? 'منشأة صغيرة/متوسطة (SME)' : 'فرد'
  const dateLabel = input.createdAt.toLocaleDateString('ar-SA', { year: 'numeric', month: 'long', day: 'numeric' })

  return `<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
<meta charset="UTF-8">
<title>تقرير القرض الأخضر الشمسي - ${input.fullName}</title>
<style>
  @page { size: A4; margin: 1.5cm; }
  * { box-sizing: border-box; }
  body { font-family: 'Tajawal', 'Cairo', 'Noto Sans Arabic', Arial, sans-serif; color: #1a1a1a; margin: 0; padding: 20px; }
  .header { background: linear-gradient(135deg, #16a34a, #0891b2); color: white; padding: 25px; border-radius: 12px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; }
  .header h1 { margin: 0; font-size: 20px; }
  .header .subtitle { font-size: 12px; opacity: 0.9; margin-top: 4px; }
  .header .stamp { text-align: center; font-size: 9px; }
  .header .stamp img { width: 70px; height: 70px; background: white; border-radius: 6px; padding: 4px; }
  .disclaimer-box { background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 10px 12px; font-size: 10px; color: #78350f; margin-bottom: 18px; line-height: 1.6; }
  .section { margin-bottom: 20px; page-break-inside: avoid; }
  .section h2 { color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 6px; font-size: 15px; margin: 0 0 10px 0; }
  .info-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 6px 20px; font-size: 12px; margin-bottom: 8px; }
  .info-row { display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px dotted #e2e8f0; }
  .info-row .label { color: #64748b; }
  .info-row .value { font-weight: 600; }
  .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 10px 0; }
  .kpi-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px; text-align: center; }
  .kpi-card .label { font-size: 9.5px; color: #64748b; margin-bottom: 3px; }
  .kpi-card .value { font-size: 17px; font-weight: 700; color: #16a34a; }
  .compare-grid { display: grid; grid-template-columns: 1fr auto 1fr; align-items: center; gap: 10px; margin: 10px 0; }
  .compare-card { background: #f8fafc; border-radius: 8px; padding: 12px; text-align: center; }
  .compare-card.a { border: 1px solid #fca5a5; }
  .compare-card.b { border: 1px solid #86efac; }
  .compare-card .title { font-size: 11px; color: #64748b; margin-bottom: 4px; }
  .compare-card .value { font-size: 15px; font-weight: 700; }
  .carbon-tags { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 8px; }
  .tag { display: inline-block; background: #ecfdf5; color: #065f46; border: 1px solid #a7f3d0; border-radius: 6px; padding: 4px 10px; font-size: 11px; }
  .footer { margin-top: 20px; padding-top: 12px; border-top: 2px solid #16a34a; font-size: 9px; color: #64748b; text-align: center; line-height: 1.6; }
  .verify-box { display: flex; align-items: center; justify-content: center; gap: 12px; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 10px; margin-top: 10px; }
  .verify-box img { width: 60px; height: 60px; }
  .verify-box .hash { font-family: monospace; font-size: 9px; word-break: break-all; color: #14532d; direction: ltr; text-align: left; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <h1>تقرير القرض الأخضر الشمسي — Eco Ledger</h1>
      <div class="subtitle">تقييم تمويلي وبيئي أولي جاهز للعرض على الجهة الممولة · ${dateLabel}</div>
    </div>
    <div class="stamp">
      <img src="${qrCodeDataUrl}" alt="dMRV Verification Stamp" />
      <div>ختم توثيق dMRV</div>
    </div>
  </div>

  <div class="disclaimer-box">
    هذا التقرير تقديري لأغراض التخطيط الأولي فقط ولا يشكل عرض تمويل ملزمًا ولا استشارة مالية أو استثمارية.
    الأرقام الفعلية تعتمد على دراسة موقع ميدانية ومطابقة عروض المقاولين وشروط الجهة الممولة النهائية.
  </div>

  <div class="section">
    <h2>بيانات مقدّم الطلب</h2>
    <div class="info-grid">
      <div class="info-row"><span class="label">الاسم</span><span class="value">${escapeHtml(input.fullName)}</span></div>
      <div class="info-row"><span class="label">البريد الإلكتروني</span><span class="value">${escapeHtml(input.email)}</span></div>
      <div class="info-row"><span class="label">نوع العميل</span><span class="value">${userTypeLabel}</span></div>
      <div class="info-row"><span class="label">${input.userType === 'sme' ? 'اسم المنشأة' : 'الهاتف'}</span><span class="value">${escapeHtml((input.userType === 'sme' ? input.companyName : input.phone) || '—')}</span></div>
    </div>
  </div>

  <div class="section">
    <h2>ملخص القرض الأخضر المقترح</h2>
    <div class="kpi-grid">
      <div class="kpi-card"><div class="label">تكلفة المنظومة التقديرية</div><div class="value">${fmtMoney(r.loan.estimatedSystemCost, r.currency)}</div></div>
      <div class="kpi-card"><div class="label">قيمة القرض المقترح</div><div class="value">${fmtMoney(r.loan.loanAmount, r.currency)}</div></div>
      <div class="kpi-card"><div class="label">القسط الشهري</div><div class="value">${fmtMoney(r.loan.monthlyPMT, r.currency)}</div></div>
      <div class="kpi-card"><div class="label">مدة التمويل</div><div class="value">${r.loan.loanTermYears} سنوات</div></div>
    </div>
  </div>

  <div class="section">
    <h2>المؤشرات المالية</h2>
    <div class="kpi-grid">
      <div class="kpi-card"><div class="label">التوفير الشهري</div><div class="value">${fmtMoney(r.cashflow.monthlySavings, r.currency)}</div></div>
      <div class="kpi-card"><div class="label">صافي التدفق الشهري (أثناء القرض)</div><div class="value">${fmtMoney(r.cashflow.netMonthlyCashflowDuringLoan, r.currency)}</div></div>
      <div class="kpi-card"><div class="label">فترة الاسترداد البسيطة</div><div class="value">${r.cashflow.simplePaybackYears ?? '—'} سنة</div></div>
      <div class="kpi-card"><div class="label">العائد التراكمي (20 سنة)</div><div class="value">${r.cashflow.cumulativeROI20yrPct ?? '—'}%</div></div>
    </div>

    <div class="compare-grid">
      <div class="compare-card a">
        <div class="title">السيناريو أ — الوضع الحالي (الشبكة)</div>
        <div class="value">${fmtMoney(r.scenarios.scenarioA_statusQuo.monthlyCost, r.currency)} / شهريًا</div>
      </div>
      <div style="font-size: 20px;">←</div>
      <div class="compare-card b">
        <div class="title">السيناريو ب — شمسي + قرض أخضر</div>
        <div class="value">${fmtMoney(r.scenarios.scenarioB_solarLoan.monthlyOutflowYear1, r.currency)} / شهريًا</div>
      </div>
    </div>
    <div style="text-align:center; font-size: 11px; color: #16a34a; font-weight: 600;">
      فرق شهري صافٍ: ${fmtMoney(r.scenarios.netMonthlyDelta, r.currency)}
    </div>
  </div>

  <div class="section">
    <h2>الأثر البيئي وجدوى شهادات الكربون</h2>
    <div class="kpi-grid">
      <div class="kpi-card"><div class="label">CO₂ متجنَّب سنويًا</div><div class="value">${fmtNum(r.carbon.avoidedCO2TonsPerYear)} طن</div></div>
      <div class="kpi-card"><div class="label">CO₂ متجنَّب (20 سنة)</div><div class="value">${fmtNum(r.carbon.avoidedCO2TonsLifetime)} طن</div></div>
      <div class="kpi-card"><div class="label">دخل كربوني محتمل سنويًا</div><div class="value">${fmtMoney(r.carbon.potentialCarbonCreditIncomeAnnual, r.currency)}</div></div>
      <div class="kpi-card"><div class="label">الإنتاج السنوي التقديري</div><div class="value">${fmtNum(r.carbon.estimatedAnnualProductionKwh)} kWh</div></div>
    </div>
    <div class="carbon-tags">
      <span class="tag">🌳 يعادل زراعة ${fmtNum(r.carbon.treesEquivalentPerYear)} شجرة سنويًا</span>
      <span class="tag">🚗 يعادل إزالة ${fmtNum(r.carbon.carsRemovedEquivalent)} سيارة من الطريق سنويًا</span>
    </div>
    <div style="font-size: 9.5px; color: #94a3b8; margin-top: 6px;">
      * دخل شهادات الكربون تقديري ومرهون بانضمام المشروع لاحقًا لمنصة Eco Ledger dMRV واعتماد جهة تحقق مستقلة.
    </div>
  </div>

  <div class="verify-box">
    <img src="${qrCodeDataUrl}" alt="QR" />
    <div>
      <div style="font-size:10px; font-weight:700; color:#14532d;">dMRV Blockchain-Ready Verification Stamp</div>
      <div class="hash">SHA-256: ${verificationHash}</div>
      <div style="font-size:9px; color:#64748b;">رمز التحقق: ${input.id.slice(0, 8).toUpperCase()} · امسح الرمز أو راجع الرابط للتحقق من صحة التقرير</div>
    </div>
  </div>

  <div class="footer">
    Eco Ledger — منصة dMRV رقمية لقياس الأثر البيئي وإصدار تقارير استدامة ESG موثوقة · تم إنشاء هذا التقرير آليًا في ${dateLabel}<br/>
    جميع القيم بعملة ${r.currency} دون تحويل عملات. هذا التقرير لا يشكل التزامًا بمنح تمويل من أي جهة.
  </div>
</body>
</html>`
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
